# Netlify configuration for Event Finder (frontend + API proxy)

# Build the frontend from the monorepo root
[build]
command = "cd frontend && npm ci && npm run build"
publish = "frontend/dist"

# Proxy API requests to your backend (update to your actual backend URL)
# If you deployed backend on Render, replace below with that URL.
[[redirects]]
from = "/api/*"
to = "https://event-finder-backend.onrender.com/api/:splat"
status = 200
force = true

# SPA fallback for React Router (must be last)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
