# Netlify configuration for unified frontend + serverless API

[build]
# Install root deps (for function bundling resolution), backend deps, and frontend deps; then build frontend
command = "npm ci && npm ci --prefix backend && npm ci --prefix frontend && npm run build --prefix frontend"
publish = "frontend/dist"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# Route /api/* to the Netlify Function
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

# SPA fallback for React Router (must be last)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
