[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm ci --prefix backend',
  'npm ci --prefix frontend'
]

[phases.build]
cmds = [
  'npm run build --prefix frontend',
  'npm run build --prefix backend'
]

[start]
cmd = 'npm run start --prefix backend'
