services:
  # Backend API Service
  - type: web
    name: event-finder-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    # Install devDependencies during build so TypeScript and @types/* are available
    buildCommand: npm ci --include=dev && npm run build
    startCommand: node dist/server.js
    nodeVersion: 20
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: event-finder-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
